# Generated by Django 4.2.7 on 2023-12-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0002_rename_nombre_inscrito_nombre_inscrito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrito',
            old_name='nombre_inscrito',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='nombre_institucion',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No Asisten')], default='RESERVADO', max_length=11),
        ),
    ]
